baseurl: '/portfolio' # the subpath of your site, e.g. /blog
url: 'https://kevin-fagan.github.io' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
    - jekyll-feed
